export type MusicalScale = { root: ScaleRoot; type: ScaleType }
export type MusicalKey = { root: ScaleRoot; type: 'major' | 'minor' }

export type ScaleRoot =
  | 'Ab'
  | 'A'
  | 'A#'
  | 'Bb'
  | 'B'
  | 'B#'
  | 'Cb'
  | 'C'
  | 'C#'
  | 'Db'
  | 'D'
  | 'D#'
  | 'Eb'
  | 'E'
  | 'E#'
  | 'Fb'
  | 'F'
  | 'F#'
  | 'Gb'
  | 'G'
  | 'G#'

// These scale names are compatible with Tonal
// https://github.com/tonaljs/tonal/tree/main/packages/scale-type
export type ScaleType =
  | 'chromatic'
  | 'major'
  | 'minor'
  | 'major pentatonic'
  | 'minor pentatonic'
  | 'major blues'
  | 'minor blues'
  | 'melodic minor'
  | 'harmonic minor'
  | 'bebop'
  | 'malkos raga'
  | 'balinese'
  | 'oriental'
  | 'flamenco'
  | 'egyptian'
  | 'persian'
  | 'diminished'
  | 'dorian'
  | 'lydian'
  | 'mixolydian'
  | 'phrygian'
  | 'locrian'
  | 'ionian pentatonic'
  | 'mixolydian pentatonic'
  | 'ritusen'
  | 'neopolitan major pentatonic'
  | 'vietnamese 1'
  | 'pelog'
  | 'kumoijoshi'
  | 'hirajoshi'
  | 'iwato'
  | 'in-sen'
  | 'lydian pentatonic'
  | 'locrian pentatonic'
  | 'minor six pentatonic'
  | 'flat three pentatonic'
  | 'flat six pentatonic'
  | 'scriabin'
  | 'whole tone pentatonic'
  | 'lydian #5P pentatonic'
  | 'lydian dominant pentatonic'
  | 'minor #7M pentatonic'
  | 'super locrian pentatonic'
  | 'minor hexatonic'
  | 'augmented'
  | 'piongio'
  | 'prometheus neopolitan'
  | 'prometheus'
  | 'mystery #1'
  | 'six tone symmetric'
  | 'whole tone'
  | "messiaen's mode #5"
  | 'locrian major'
  | 'double harmonic lydian'
  | 'altered'
  | 'locrian #2'
  | 'mixolydian b6'
  | 'lydian dominant'
  | 'lydian augmented'
  | 'dorian b2'
  | 'ultralocrian'
  | 'locrian 6'
  | 'augmented heptatonic'
  | 'dorian #4'
  | 'lydian diminished'
  | 'leading whole tone'
  | 'lydian minor'
  | 'phrygian dominant'
  | 'neopolitan major'
  | 'harmonic major'
  | 'double harmonic major'
  | 'hungarian minor'
  | 'hungarian major'
  | 'todi raga'
  | 'enigmatic'
  | 'major augmented'
  | 'lydian #9'
  | "messiaen's mode #4"
  | 'purvi raga'
  | 'spanish heptatonic'
  | 'bebop minor'
  | 'bebop major'
  | 'bebop locrian'
  | 'ichikosucho'
  | 'minor six diminished'
  | 'half-whole diminished'
  | 'kafi raga'
  | "messiaen's mode #6"
  | 'composite blues'
  | "messiaen's mode #3"
  | "messiaen's mode #7"
