export const availableChords = [
  'major',
  'minor',
  'major seventh',
  'minor seventh',
  'dominant seventh',
  'diminished',
  'augmented',
  'minor augmented',
  'suspended second',
  'suspended fourth',
  'minor sixth',
  'major ninth',
  'minor ninth',
  'dominant ninth',
  'eleventh',
  'minor eleventh',
  'major thirteenth',
  'minor thirteenth',
]

export const availableScales = [
  'chromatic',
  'major',
  'minor',
  'major pentatonic',
  'minor pentatonic',
  'major blues',
  'minor blues',
  'melodic minor',
  'harmonic minor',
  'bebop',
  'malkos raga',
  'balinese',
  'oriental',
  'flamenco',
  'egyptian',
  'persian',
]
