export const availableChords = [
  'major',
  'minor',
  'major seventh',
  'minor seventh',
  'suspended fourth',
  'suspended fourth seventh',
  'augmented',
  'major seventh flat sixth',
  'augmented seventh',
  'dominant seventh',
  'sixth',
  'major seventh sharp eleventh',
  'lydian dominant seventh',
  'minor augmented',
  'minor/major seventh',
  'minor sixth',
  'diminished',
  'half-diminished',
  'diminished seventh',
  'dominant sharp ninth',
  'suspended second',
  'eleventh',
  'major ninth',
  'dominant ninth',
  'sixth added ninth',
  'major thirteenth',
  'dominant thirteenth',
  'major sharp eleventh (lydian)',
  'minor/major ninth',
  'minor ninth',
  'minor thirteenth',
  'minor eleventh',
  'suspended fourth flat ninth',
  'altered',
  'dominant flat ninth',
]

export const availableScales = [
  'chromatic',
  'major',
  'minor',
  'major pentatonic',
  'minor pentatonic',
  'major blues',
  'minor blues',
  'melodic minor',
  'harmonic minor',
  'bebop',
  'malkos raga',
  'balinese',
  'oriental',
  'flamenco',
  'egyptian',
  'persian',
]
